/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filetransfer.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXFNAME))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_chunk (XDR *xdrs, file_chunk *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, MAXCHUNK))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_last))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_upload_arg (XDR *xdrs, upload_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_file_chunk (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_upload_res (XDR *xdrs, upload_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_download_arg (XDR *xdrs, download_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chunk_reply (XDR *xdrs, chunk_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, MAXCHUNK))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_last))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_download_res (XDR *xdrs, download_res *objp)
{
	register int32_t *buf;

	 if (!xdr_chunk_reply (xdrs, objp))
		 return FALSE;
	return TRUE;
}
