/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILETRANSFER_H_RPCGEN
#define _FILETRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXFNAME 256
#define MAXCHUNK 4096

typedef char *filename;

struct upload_chunk {
	filename name;
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int offset;
	bool_t is_last;
};
typedef struct upload_chunk upload_chunk;

typedef upload_chunk upload_arg;

typedef int upload_res;

struct download_arg_s {
	filename name;
	int offset;
};
typedef struct download_arg_s download_arg_s;

typedef download_arg_s download_arg;

struct chunk_reply {
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int data_len;
	bool_t is_last;
};
typedef struct chunk_reply chunk_reply;

typedef chunk_reply download_res;

#define FILE_TRANSFER_PROG 0x20000001
#define FILE_TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define UPLOAD_FILE 1
extern  upload_res * upload_file_1(upload_arg *, CLIENT *);
extern  upload_res * upload_file_1_svc(upload_arg *, struct svc_req *);
#define DOWNLOAD_FILE 2
extern  download_res * download_file_1(download_arg *, CLIENT *);
extern  download_res * download_file_1_svc(download_arg *, struct svc_req *);
extern int file_transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UPLOAD_FILE 1
extern  upload_res * upload_file_1();
extern  upload_res * upload_file_1_svc();
#define DOWNLOAD_FILE 2
extern  download_res * download_file_1();
extern  download_res * download_file_1_svc();
extern int file_transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_upload_chunk (XDR *, upload_chunk*);
extern  bool_t xdr_upload_arg (XDR *, upload_arg*);
extern  bool_t xdr_upload_res (XDR *, upload_res*);
extern  bool_t xdr_download_arg_s (XDR *, download_arg_s*);
extern  bool_t xdr_download_arg (XDR *, download_arg*);
extern  bool_t xdr_chunk_reply (XDR *, chunk_reply*);
extern  bool_t xdr_download_res (XDR *, download_res*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_upload_chunk ();
extern bool_t xdr_upload_arg ();
extern bool_t xdr_upload_res ();
extern bool_t xdr_download_arg_s ();
extern bool_t xdr_download_arg ();
extern bool_t xdr_chunk_reply ();
extern bool_t xdr_download_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILETRANSFER_H_RPCGEN */
