/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "filetransfer.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

upload_res *
upload_file_1(upload_arg *argp, CLIENT *clnt)
{
	static upload_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UPLOAD_FILE,
		(xdrproc_t) xdr_upload_arg, (caddr_t) argp,
		(xdrproc_t) xdr_upload_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

download_res *
download_file_1(download_arg *argp, CLIENT *clnt)
{
	static download_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DOWNLOAD_FILE,
		(xdrproc_t) xdr_download_arg, (caddr_t) argp,
		(xdrproc_t) xdr_download_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
