#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "filetransfer.h"   // generated by rpcgen

#define CHUNK 4096

//Upload a local file -> server

void upload_file(CLIENT *clnt, const char *local, const char *remote) {
    FILE *f = fopen(local, "rb");
    if (!f) {
        perror("fopen");
        return;
    }

    char buffer[CHUNK];
    size_t n;

    while ((n = fread(buffer, 1, CHUNK, f)) > 0) {
        upload_arg arg;

        arg.name = (char *)remote;
        arg.data.data_len = n;
        arg.data.data_val = buffer;
        arg.is_last = feof(f);

        upload_res *res = upload_file_1(&arg, clnt);
        if (!res || *res != 0) {
            fprintf(stderr, "Upload failed\n");
            fclose(f);
            return;
        }

        if (arg.is_last) break;
    }

    fclose(f);
    printf("Upload completed.\n");
}

//Download server file -> local file

void download_file(CLIENT *clnt, const char *remote, const char *local) {
    FILE *f = fopen(local, "wb");
    if (!f) {
        perror("fopen");
        return;
    }

    download_arg arg = (char *)remote;

    while (1) {
        download_res *reply = download_file_1(&arg, clnt);

        if (!reply) {
            fprintf(stderr, "RPC download failed\n");
            fclose(f);
            return;
        }

        fwrite(reply->data.data_val, 1, reply->data.data_len, f);

        if (reply->is_last) break;
    }

    fclose(f);
    printf("Download completed.\n");
}

int main(int argc, char **argv) {
    if (argc < 5) {
        printf("Usage:\n");
        printf("  Upload:   %s <server_ip> upload   <localfile> <remotefile>\n", argv[0]);
        printf("  Download: %s <server_ip> download <remotefile> <localfile>\n", argv[0]);
        return 1;
    }

    char *host = argv[1];
    char *mode = argv[2];

    CLIENT *clnt = clnt_create(host, FILE_TRANSFER_PROG, FILE_TRANSFER_VERS, "tcp");
    if (!clnt) {
        clnt_pcreateerror("clnt_create");
        return 1;
    }

    if (strcmp(mode, "upload") == 0) {
        upload_file(clnt, argv[3], argv[4]);
    }
    else if (strcmp(mode, "download") == 0) {
        download_file(clnt, argv[3], argv[4]);
    }
    else {
        printf("Invalid mode.\n");
    }

    clnt_destroy(clnt);
    return 0;
}
