#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "filetransfer.h"    // generated by rpcgen

int main(int argc, char *argv[]) {
    if (argc != 3) {
        printf("Usage: %s <server_ip> <filename>\n", argv[0]);
        exit(1);
    }

    char *server = argv[1];
    char *filename = argv[2];

    // Create RPC client handle
    CLIENT *cl = clnt_create(server, FILETRANSFER, FILETRANSFER_V1, "tcp");
    if (cl == NULL) {
        clnt_pcreateerror(server);
        exit(1);
    }

    // Call RPC: getchunk(filename)
    filechunk *chunk = getchunk_1(&filename, cl);

    if (chunk == NULL) {
        clnt_perror(cl, "RPC failed");
        exit(1);
    }

    if (chunk->data.data_len == 0) {
        printf("Server sent empty file or error.\n");
        exit(1);
    }

    // Save to local file
    FILE *out = fopen("received.bin", "wb");
    if (!out) {
        perror("Cannot create output file");
        exit(1);
    }

    fwrite(chunk->data.data_val, 1, chunk->data.data_len, out);
    fclose(out);

    printf("Received %d bytes and saved to received.bin\n",
        chunk->data.data_len);

    // Cleanup
    clnt_destroy(cl);
    return 0;
}
